name: pczn_dev_kit
description: A comprehensive Flutter package offering a versatile toolbox of utilities, helpers, and extensions to streamline development workflows.
version: 1.2.1+4
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hydrated_bloc: ^9.1.5
  random_string: ^2.3.1
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  import_sorter: ^4.6.0
  mockito: ^5.4.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
